// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNinja struct {
	Name           *string `json:"name"`
	Rank           *string `json:"rank"`
	MainStyle      *string `json:"mainStyle"`
	Village        *string `json:"village"`
	Status         *string `json:"status"`
	NumberOfJutsus *int    `json:"numberOfJutsus"`
}

type Ninja struct {
	Name           *string `json:"name"`
	Rank           *string `json:"rank"`
	MainStyle      *string `json:"mainStyle"`
	Village        *string `json:"village"`
	Status         *string `json:"status"`
	NumberOfJutsus *int    `json:"numberOfJutsus"`
}

type ResponseMessage struct {
	Message string `json:"message"`
}
